http://localhost:8081/auth/alta/

Content-Type: : application/json
//Super Usuario
{
    "email": "admin@admin.com",
    "username": "admin",
    "password": "admin"
}
{
    "email": "user@gmail.com",
    "username": "user",
    "password": "contraseña"
}