# Generated by Django 3.2.3 on 2021-06-24 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesionales', '0002_profesionales_domicilio'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profesionales',
            name='tel_celular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='profesionales',
            name='tel_fijo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
