#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.9

pipelines:
  default:
    - parallel:
#      - step:
#          name: Test
#          caches:
#            - pip
#          script:
#            - cd backend
#            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#            - pip install pytest
#            - pytest -v tests/* --junitxml=test-reports/report.xml
      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
            - cd backend
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
      - step:
          name: Deploy to heroku
          script: # Modify the commands below to build your repository.
            - git push https://heroku:3c58e65e-1344-49c9-a8e6-fbffcc004e58@git.heroku.com/federaciondemutuales_beta.git HEAD


