#  Template python-build

#  This template allows you to validate your python code.
#  The workflow allows running tests and code linting on the default branch.

image: python:3.9

pipelines:
  default:
    - parallel:
#      - step:
#          name: Test
#          caches:
#            - pip
#          script:
#            - cd backend
#            - if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
#            - pip install pytest
#            - pytest -v tests/* --junitxml=test-reports/report.xml
      - step:
          name: Lint code
          script:
            # Enforce style consistency across Python projects https://flake8.pycqa.org/en/latest/manpage.html
            - cd backend
            - pip install flake8
            - flake8 . --extend-exclude=dist,build --show-source --statistics
      - step:
          name: Create ZIP_FILE
          script:
            - tar czfv my_app.tgz .
          artifacts:
            - my_app.tgz
      - step:
          name: Deploy to production
          deployment: production
          caches:
            - pip
          script:
            - pipe: atlassian/heroku-deploy:0.1.1
              variables:
                HEROKU_API_KEY: 3c58e65e-1344-49c9-a8e6-fbffcc004e58
                HEROKU_APP_NAME: federacion
                ZIP_FILE: "my_app.tgz"

