# Generated by Django 3.2.3 on 2021-06-21 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profesionales',
            fields=[
                ('id_medico', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido_y_nombre', models.CharField(max_length=80)),
                ('dni', models.IntegerField(unique=True)),
                ('localidad', models.CharField(max_length=30)),
                ('provincia', models.CharField(choices=[('Buenos Aires', '1- Buenos Aires'), ('Catamarca', '2- Catamarca'), ('Chaco', '3- Chaco'), ('Chubut', '4- Chubut'), ('Córdoba', '5- Córdoba'), ('Corrientes', '6- Corrientes'), ('Entre Ríos', '7- Entre Ríos'), ('Formosa', '8- Formosa'), ('Jujuy', '9- Jujuy'), ('La Pampa', '10- La Pampa'), ('La Rioja', '11- La Rioja'), ('Mendoza', '12- Mendoza'), ('Misiones', '13- Misiones'), ('Neuquén', '14- Neuquén'), ('Río Negro', '15- Río Negro'), ('Salta', '16- Salta'), ('San Juan', '17- San Juan'), ('San Luis', '18- San Luis'), ('Santa Cruz', '19- Santa Cruz'), ('Santa Fe', '20- Santa Fe'), ('Santiago del Estero', '21- Santiago del Estero'), ('Tierra del Fuego', '22- Tierra del Fuego'), ('Tucumán', '23- Tucumán')], max_length=30)),
                ('fecha_ingreso', models.DateField()),
                ('especialidad', models.CharField(blank=True, max_length=40, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('tel_fijo', models.IntegerField()),
                ('tel_celular', models.IntegerField()),
                ('matricula', models.IntegerField(unique=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'profesional',
                'verbose_name_plural': 'profesionales',
            },
        ),
    ]
