# Generated by Django 3.2.3 on 2021-06-21 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Profesionales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profesionales',
            name='domicilio',
            field=models.CharField(default='Av San Juan 234', max_length=50),
            preserve_default=False,
        ),
    ]
