deptos_tucuman = [
    ("Burruyacú", "1- Burruyacú"),
    ("Capital", "2- Capital"),
    ("Chicligasta", "3- Chicligasta"),
    ("Cruz Alta", "4- Cruz Alta"),
    ("Famaillá", "5- Famaillá"),
    ("Graneros", "6- Graneros"),
    ("Juan Bautista Alberdi", "7- Juan Bautista Alberdi"),
    ("La Cocha", "8- La Cocha"),
    ("Leales", "9- Leales"),
    ("Lules", "10- Lules"),
    ("Monteros", "11- Monteros"),
    ("Río Chico", "12- Río Chico"),
    ("Simoca", "13- Simoca"),
    ("Tafí del Valle", "14- Tafí del Valle"),
    ("Tafí Viejo", "15- Tafí Viejo"),
    ("Trancas", "16- Trancas"),
    ("Yerba Buena", "17- Yerba Buena"),
]

provincias = [
    ("Buenos Aires", "1- Buenos Aires"),
    ("Catamarca", "2- Catamarca"),
    ("Chaco", "3- Chaco"),
    ("Chubut", "4- Chubut"),
    ("Córdoba", "5- Córdoba"),
    ("Corrientes", "6- Corrientes"),
    ("Entre Ríos", "7- Entre Ríos"),
    ("Formosa", "8- Formosa"),
    ("Jujuy", "9- Jujuy"),
    ("La Pampa", "10- La Pampa"),
    ("La Rioja", "11- La Rioja"),
    ("Mendoza", "12- Mendoza"),
    ("Misiones", "13- Misiones"),
    ("Neuquén", "14- Neuquén"),
    ("Río Negro", "15- Río Negro"),
    ("Salta", "16- Salta"),
    ("San Juan", "17- San Juan"),
    ("San Luis", "18- San Luis"),
    ("Santa Cruz", "19- Santa Cruz"),
    ("Santa Fe", "20- Santa Fe"),
    ("Santiago del Estero", "21- Santiago del Estero"),
    ("Tierra del Fuego", "22- Tierra del Fuego"),
    ("Tucumán", "23- Tucumán"),
]

comumas_municipios=[('Acheral', 'Acheral'), ('Agua Dulce y La Soledad', 'Agua Dulce y La Soledad'), ('Aguilares', 'Aguilares'), ('Alderetes', 'Alderetes'), ('Alpachiri y El Molino', 'Alpachiri y El Molino'), ('Alto Verde y Los Gucheas', 'Alto Verde y Los Gucheas'), ('Amaichá del Valle', 'Amaichá del Valle'), ('Amberes', 'Amberes'), ('Anca Juli', 'Anca Juli'), ('Arcadia', 'Arcadia'), ('Atahona', 'Atahona'), ('Banda del Río Salí', 'Banda del Río Salí'), ('Bella Vista', 'Bella Vista'), ('Buena Vista', 'Buena Vista'), ('Burruyacú', 'Burruyacú'), ('Capitán Cáceres', 'Capitán Cáceres'), ('Cevil Redondo', 'Cevil Redondo'), ('Choromoro', 'Choromoro'), ('Ciudacita', 'Ciudacita'), ('Colalao del Valle', 'Colalao del Valle'), ('Colombres', 'Colombres'), ('Concepción', 'Concepción'), ('Delfín Gallo (Ex Ingenio Esperanza', 'Delfín Gallo (Ex Ingenio Esperanza'), ('El Bracho y El Cevilar', 'El Bracho y El Cevilar'), ('El Cadillal', 'El Cadillal'), ('El Cercado', 'El Cercado'), ('El Chañar', 'El Chañar'), ('El Manantial', 'El Manantial'), ('El Mojón', 'El Mojón'), ('El Mollar', 'El Mollar'), ('El Naranjito', 'El Naranjito'), ('El Naranjo y El Sunchal', 'El Naranjo y El Sunchal'), ('El Polear', 'El Polear'), ('El Puestito', 'El Puestito'), ('El Sacrificio', 'El Sacrificio'), ('El Timbó', 'El Timbó'), ('Escaba', 'Escaba'), ('Esquina y Mancopa', 'Esquina y Mancopa'), ('Estación Araox y Tacanas', 'Estación Araox y Tacanas'), ('Famaillá', 'Famaillá'), ('Gastona y Belicha', 'Gastona y Belicha'), ('Gobernador Garmendia', 'Gobernador Garmendia'), ('Gobernador Piedrabuena', 'Gobernador Piedrabuena'), ('Graneros', 'Graneros'), ('Huasa Pampa', 'Huasa Pampa'), ('Juan Bautista Alberdi', 'Juan Bautista Alberdi'), ('La Cocha', 'La Cocha'), ('La Esperanza', 'La Esperanza'), ('La Florida y Luisiana', 'La Florida y Luisiana'), ('La Ramada y La Cruz', 'La Ramada y La Cruz'), ('La Trinidad', 'La Trinidad'), ('Lamadrid', 'Lamadrid'), ('Las Cejas', 'Las Cejas'), ('Las Talas', 'Las Talas'), ('Las Talitas', 'Las Talitas'), ('Los Bulacio y Los Villagra', 'Los Bulacio y Los Villagra'), ('Los Gómez', 'Los Gómez'), ('Los Nogales', 'Los Nogales'), ('Los Pereyra', 'Los Pereyra'), ('Los Puestos', 'Los Puestos'), ('Los Pérez', 'Los Pérez'), ('Los Ralos', 'Los Ralos'), ('Los Sarmientos y La Tipa', 'Los Sarmientos y La Tipa'), ('Los Sosas', 'Los Sosas'), ('Lules', 'Lules'), ('Manuel García Fernández', 'Manuel García Fernández'), ('Manuela Pedraza', 'Manuela Pedraza'), ('Medinas', 'Medinas'), ('Monte Bello', 'Monte Bello'), ('Monteagudo', 'Monteagudo'), ('Monteros', 'Monteros'), ('Padre Monti', 'Padre Monti'), ('Pampa Mayo', 'Pampa Mayo'), ('Quilmes y Los Sueldos', 'Quilmes y Los Sueldos'), ('Raco', 'Raco'), ('Ranchillos y San Miguel', 'Ranchillos y San Miguel'), ('Rumi Punco', 'Rumi Punco'), ('Río Chico y Nueva Trinidad', 'Río Chico y Nueva Trinidad'), ('Río Colorado', 'Río Colorado'), ('Río Seco', 'Río Seco'), ('San Andrés', 'San Andrés'), ('San Felipe y Santa Bárbara', 'San Felipe y Santa Bárbara'), ('San Ignacio', 'San Ignacio'), ('San Javier', 'San Javier'), ('San José de la Cocha', 'San José de la Cocha'), ('San Miguel de Tucumán', 'San Miguel de Tucumán'), ('San Pablo y Villa Nougués', 'San Pablo y Villa Nougués'), ('San Pedro de Colalao', 'San Pedro de Colalao'), ('San Pedro y San Antonio', 'San Pedro y San Antonio'), ('Santa Ana', 'Santa Ana'), ('Santa Cruz y La Tuna', 'Santa Cruz y La Tuna'), ('Santa Lucía', 'Santa Lucía'), ('Santa Rosa de Leales', 'Santa Rosa de Leales'), ('Santa Rosa y Los Rojo', 'Santa Rosa y Los Rojo'), ('Sargento Moya', 'Sargento Moya'), ('Siete de Abril', 'Siete de Abril'), ('Simoca', 'Simoca'), ('Soldado Maldonado', 'Soldado Maldonado'), ('Taco Ralo', 'Taco Ralo'), ('Tafí Viejo', 'Tafí Viejo'), ('Tafí del Valle', 'Tafí del Valle'), ('Tapia', 'Tapia'), ('Teniente Berdina', 'Teniente Berdina'), ('Trancas', 'Trancas'), ('Villa Belgrano', 'Villa Belgrano'), ('Villa Benjamín Araoz', 'Villa Benjamín Araoz'), ('Villa Chigligasta', 'Villa Chigligasta'), ('Villa Quinteros', 'Villa Quinteros'), ('Villa de Leales', 'Villa de Leales'), ('Yerba Buena', 'Yerba Buena'), ('Yánima', 'Yánima')]