# Generated by Django 3.2.3 on 2021-06-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='socios',
            fields=[
                ('numero_socio', models.IntegerField(primary_key=True, serialize=False)),
                ('apellido_nombre', models.CharField(max_length=80)),
                ('dni', models.IntegerField()),
                ('calle', models.CharField(max_length=50)),
                ('localidad', models.CharField(max_length=30)),
                ('departamento', models.CharField(max_length=30)),
                ('cod_postal', models.IntegerField()),
                ('fecha_nacimiento', models.DateField()),
                ('edad', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
                ('tel_fijo', models.IntegerField()),
                ('tel_celular', models.IntegerField()),
                ('imagen_dni', models.ImageField(blank=True, null=True, upload_to='blog')),
                ('carencia', models.DateField(blank=True, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'socio',
                'verbose_name_plural': 'socios',
            },
        ),
    ]
