# Generated by Django 3.2.3 on 2021-06-21 00:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0003_alter_socios_departamento'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='socios',
            name='imagen_dni',
        ),
    ]
