# Generated by Django 3.2.3 on 2021-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Socios', '0004_remove_socios_imagen_dni'),
    ]

    operations = [
        migrations.AlterField(
            model_name='socios',
            name='tel_celular',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='socios',
            name='tel_fijo',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
